version: "3.9"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g     # JVM heap tuning
    ports:
      - "9200:9200"   # REST API
      - "9300:9300"   # transport
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 >/dev/null"]
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: 60s   # give ts time to initialize since its so slooooooowwww

  worker1:
    build: ./worker
    container_name: worker2
    ports:
      - "6000:6000"
    depends_on:
      elasticsearch:
        condition: service_healthy
