# services:
#   gateway:
#     build: ./gateway
#     volumes:
#       - ./gateway/logs:/app/logs
#     container_name: gateway
#     ports:
#       - "5000:5000"
#     depends_on:
#       - etcd

#   etcd:
#     image: gcr.io/etcd-development/etcd:v3.5.13
#     container_name: etcd
#     command: >
#       etcd
#       --advertise-client-urls http://0.0.0.0:2379
#       --listen-client-urls http://0.0.0.0:2379
#     ports:
#       - "2379:2379"
#       - "2380:2380"


services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: ${NODE_NAME}
    network_mode: "host"
    environment:
      - cluster.name=distributed-log-cluster
      - node.name=${NODE_NAME}
      - discovery.seed_hosts=${WORKER_1_IP},${WORKER_2_IP},${WORKER_3_IP}
      - cluster.initial_master_nodes=es-node-1,es-node-2,es-node-3
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=Xms1g -Xmx1g
    restart: always
    volumes:
      - es_data:/usr/share/elasticsearch/data
    
volumes:
  es_data:
    name: ${NODE_NAME}_data